#Application
spring.application.name=Alerte Rappel - API
spring.main.banner-mode=off

#Server
server.port=${PORT:8080}
spring.threads.virtual.enabled=true
server.shutdown=graceful
spring.jackson.default-property-inclusion=NON_EMPTY

#Data
data.path=${DATA_PATH:data}

#Sources
source.rappelconso.name=Rappel Conso
source.rappelconso.base-url=https://data.economie.gouv.fr
source.rappelconso.dataset=rappelconso-v2-gtin-espaces
source.rappelconso.cron=0 */15 * * * *
source.rapex.name=Rapex
source.rapex.base-url=https://public.opendatasoft.com
source.rapex.dataset=healthref-europe-rapex-fr
source.rapex.cron=0 0 * * * *
source.rapex.get-base-url=https://ec.europa.eu/safety-gate-alerts/public/api/
source.rapex.get-path=notification
source.rapex.translation-path=translations
